name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Linting
        run: |
          source venv/bin/activate
          pip install flake8
          flake8 src/

      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest tests/

      - name: Build and Push Docker Image
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t facility-feed-service .
          docker tag facility-feed-service ${{ secrets.DOCKER_USERNAME }}/facility-feed-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/facility-feed-service:latest